<?php

namespace App\Exports;

use App\Models\Owner;
use App\Services\AnalyticsPeriod;
use App\Services\RevenueAnalyticsService;
use Maatwebsite\Excel\Concerns\FromArray;
use Maatwebsite\Excel\Concerns\WithTitle;

/**
 * Every figure here comes from RevenueAnalyticsService — never re-summed —
 * so this sheet can never silently drift from the Overview page or the
 * Transactions sheet for the same period.
 */
class SummarySheet implements FromArray, WithTitle
{
    public function __construct(
        private Owner $owner,
        private AnalyticsPeriod $period,
        private RevenueAnalyticsService $revenueAnalytics,
    ) {}

    public function array(): array
    {
        $owner = $this->owner;
        $period = $this->period;
        $analytics = $this->revenueAnalytics;

        $rows = [
            ['Financial Summary'],
            ['Period', $period->label],
            ['Date Range', $period->startDate().' to '.$period->endDate()],
            [],
            ['Total Revenue', $analytics->totalRevenue($owner, $period)],
            ['Booking Revenue', $analytics->bookingRevenue($owner, $period)],
            ['Product Revenue', $analytics->saleRevenue($owner, $period)],
            ['Average Booking Value', $analytics->averageBookingValue($owner, $period) ?? 0],
            [],
            ['Revenue by Room'],
            ['Room', 'Bookings', 'Revenue'],
        ];

        foreach ($analytics->revenueByRoom($owner, $period) as $row) {
            $rows[] = [$row['room_name'], $row['bookings'], $row['revenue']];
        }

        $rows[] = [];
        $rows[] = ['Revenue by Room Type'];
        $rows[] = ['Type', 'Bookings', 'Revenue'];
        foreach ($analytics->revenueByRoomType($owner, $period) as $row) {
            $rows[] = [$row['type'], $row['bookings'], $row['revenue']];
        }

        $rows[] = [];
        $rows[] = ['Revenue by Product'];
        $rows[] = ['Product', 'Quantity', 'Revenue'];
        foreach ($analytics->revenueByProduct($owner, $period) as $row) {
            $rows[] = [$row['name'], $row['quantity'], $row['revenue']];
        }

        $rows[] = [];
        $rows[] = ['Generated At', now()->toDateTimeString()];
        $rows[] = ['Generated By', $this->currentActorName()];

        return $rows;
    }

    public function title(): string
    {
        return 'Summary';
    }

    private function currentActorName(): string
    {
        $staff = auth('staff')->user();

        return $staff?->name ?? $this->owner->business_name ?? 'Owner';
    }
}
